Added RSC option to generate executable + shell-cmd primitives in c and js

diff --git a/src/rsc b/src/rsc
--- a/src/rsc
+++ b/src/rsc
@@ -35,40 +35,39 @@ LASTSOURCE=""
 
 usage()
 {
-  echo "usage: $0 [-t target] [-c compiler] [-o output] [-l lib] [-m] [file.scm ...]"
-  echo "where"
-  echo "  target defaults to rvm and is otherwise one of js, py, sh, c, ..."
-  echo "  compiler defaults to \$RSC_COMPILER which defaults to"
-  echo "    \"\$RSC_SCHEME_INTERPRETER $ROOTDIR/rsc.scm\" where"
-  echo "    \$RSC_SCHEME_INTERPRETER defaults to \"gsi -:r4rs\" (the Gambit interpreter in mode r4rs)"
-  echo "  output defaults to last file.scm suffixed with .target"
-  echo "  lib defaults to r4rs-tc (r4rs standard library with type checking)"
-  echo "  if there is no file.scm or it is -, the source code is read from stdin"
-  echo "examples:"
-  echo "  $0 -t js prog.scm   # generates prog.scm.js using Gambit interpreter"
-  echo "  RSC_SCHEME_INTERPRETER=guile $0 -t js prog.scm # same using Guile"
-  echo "  $0 -t js -l max rsc.scm    # generates rsc.scm.js"
-  echo "  $0 -t py -l max -c \"node rsc.scm.js\" rsc.scm  # generates rsc.scm.py using nodejs running rsc.scm.js"
-  echo "  RSC_COMPILER=\"node rsc.scm.js\" $0 -t py -l max rsc.scm # same with environment variable"
+    echo "usage: $0 [-t target] [-c compiler] [-o output] [-l lib] [-m] [file.scm ...]"
+    echo "where"
+    echo "  target defaults to rvm and is otherwise one of js, py, sh, c, ..."
+    echo "  compiler defaults to \$RSC_COMPILER which defaults to"
+    echo "    \"\$RSC_SCHEME_INTERPRETER $ROOTDIR/rsc.scm\" where"
+    echo "    \$RSC_SCHEME_INTERPRETER defaults to \"gsi -:r4rs\" (the Gambit interpreter in mode r4rs)"
+    echo "  output defaults to last file.scm suffixed with .target"
+    echo "  lib defaults to r4rs-tc (r4rs standard library with type checking)"
+    echo "  if there is no file.scm or it is -, the source code is read from stdin"
+    echo "examples:"
+    echo "  $0 -t js prog.scm   # generates prog.scm.js using Gambit interpreter"
+    echo "  RSC_SCHEME_INTERPRETER=guile $0 -t js prog.scm # same using Guile"
+    echo "  $0 -t js -l max rsc.scm    # generates rsc.scm.js"
+    echo "  $0 -t py -l max -c \"node rsc.scm.js\" rsc.scm  # generates rsc.scm.py using nodejs running rsc.scm.js"
+    echo "  RSC_COMPILER=\"node rsc.scm.js\" $0 -t py -l max rsc.scm # same with environment variable"
 }
 
 
 if [ "$RSC_SCHEME_INTERPRETER" = "" ]; then
-  RSC_SCHEME_INTERPRETER="gsi -:r4rs"
+    RSC_SCHEME_INTERPRETER="gsi -:r4rs"
 fi
 
 if [ "$COMPILER" = "" ]; then
-  if [ "$RSC_COMPILER" = "" ]; then
-    COMPILER="$RSC_SCHEME_INTERPRETER $ROOTDIR/rsc.scm"
-  else
-    COMPILER="$RSC_COMPILER"
-  fi
+    if [ "$RSC_COMPILER" = "" ]; then
+        COMPILER="$RSC_SCHEME_INTERPRETER $ROOTDIR/rsc.scm"
+    else
+        COMPILER="$RSC_COMPILER"
+    fi
 fi
 
-
 if ! $COMPILER "$@"; then
-  echo "*** compilation error:"
-  cat "$RVM.temp" # print errors
-  rm "$RVM.temp"
-  exit 1
+    echo "*** compilation error:"
+    cat "$RVM.temp" # print errors
+    rm "$RVM.temp"
+    exit 1
 fi
