Optimizing the repl r4rs

diff --git a/src/rvm-size b/src/rvm-size
--- a/src/rvm-size
+++ b/src/rvm-size
@@ -1,5 +1,4 @@
-echo "(repl)" > ./repl-size.scm
-if ! gsi ./rsc.scm -t asm -l r4rs -o repl-size.asm ./repl-size.scm; then
+if ! gsi ./rsc.scm -t asm -l r4rs -o repl-size.asm ./repl-r4rs.scm; then
     echo "Error: Could not compile repl.scm"
     exit 1
 fi
@@ -13,9 +12,26 @@ case $1 in
     "-h") ls -lh ./repl-size.exe | awk '{print $5}' ;;
     *) ls -l ./repl-size.exe | awk '{print $5}' ;;
 esac
+echo -n "$(ls -l ./repl-size.exe | awk '{print $5}') " >> rvm-sizes.log
+
+rm ./repl-size.exe 
+rm ./repl-size.asm
+
+if ! gsi ./rsc.scm -t asm -e skip -l r4rs -o repl-size.asm ./repl-r4rs.scm; then
+    echo "Error: Could not compile repl.scm"
+    exit 1
+fi
+if ! nasm repl-size.asm -o repl-size.exe; then 
+    echo "Error: Could not assemble repl.asm"
+    exit 1
+fi
+
+case $1 in
+    "-h") ls -lh ./repl-size.exe | awk '{print $5}' ;;
+    *) ls -l ./repl-size.exe | awk '{print $5}' ;;
+esac
 
 ls -l ./repl-size.exe | awk '{print $5}' >> rvm-sizes.log
 
 rm ./repl-size.exe 
-rm ./repl-size.scm
 rm ./repl-size.asm
